-----------------해당 계정 내에 존재하는 DB 객체들 삭제하는 PLSQL문------------------
-- 해당 계정의 모든 트리거 삭제
BEGIN
FOR C IN (SELECT * FROM USER_TRIGGERS) LOOP
  EXECUTE IMMEDIATE 'DROP TRIGGER '||C.TRIGGER_NAME;
END LOOP;
END;
/
--해당 계정의 모든테이블 및 제약조건 삭제
BEGIN
    FOR C IN (SELECT * FROM USER_TABLES) LOOP
    EXECUTE IMMEDIATE ('DROP TABLE "'||C.TABLE_NAME||'" CASCADE CONSTRAINTS');
    END LOOP;
END;
/
--해당 계정의 모든 시퀀스 삭제
BEGIN
FOR C IN (SELECT * FROM USER_SEQUENCES) LOOP
  EXECUTE IMMEDIATE 'DROP SEQUENCE '||C.SEQUENCE_NAME;
END LOOP;
END;
/
--해당 계정의 모든 뷰 삭제
BEGIN
FOR C IN (SELECT * FROM USER_VIEWS) LOOP
  EXECUTE IMMEDIATE 'DROP VIEW '||C.VIEW_NAME;
END LOOP;
END;
/
-- 해당 계정의 모든 패키지 삭제
BEGIN
  FOR C IN (SELECT * FROM USER_OBJECTS WHERE OBJECT_TYPE = 'PACKAGE') LOOP
    EXECUTE IMMEDIATE 'DROP PACKAGE ' || C.OBJECT_NAME;
  END LOOP;
END;
/
-- 모든 패키지 바디 삭제
BEGIN
  FOR C IN (SELECT OBJECT_NAME FROM USER_OBJECTS WHERE OBJECT_TYPE = 'PACKAGE BODY') LOOP
    EXECUTE IMMEDIATE 'DROP PACKAGE BODY ' || C.OBJECT_NAME;
  END LOOP;
END;
/

SET DEFINE OFF;

CREATE TABLE "PAYMENT" (
	"PAY_NO"	NUMBER		NOT NULL,
	"MEM_NO"	NUMBER		NULL,
	"PAY_TYPE"	CHAR(1)		NULL,
	"PAY_AMOUNT"	NUMBER		NULL,
	"PAY_POINT"	NUMBER		NULL,
	"PAY_STATUS"	CHAR(1)		NULL,
	"APPROVAL_NO"	NUMBER		NULL,
	"PAY_DATE"	DATE		NULL,
	"PAY_REGIST"	DATE	DEFAULT SYSDATE	NULL
);

COMMENT ON COLUMN "PAYMENT"."PAY_TYPE" IS '카드(C)|카카오(K)|네이버(N)|무통장(B)';

COMMENT ON COLUMN "PAYMENT"."PAY_AMOUNT" IS '실제 결제된 금액';

COMMENT ON COLUMN "PAYMENT"."PAY_POINT" IS '충전된 포인트';

COMMENT ON COLUMN "PAYMENT"."PAY_STATUS" IS '(R)EADY | (P)AID | (C)ANCEL';

COMMENT ON COLUMN "PAYMENT"."APPROVAL_NO" IS '결제승인번호';

COMMENT ON COLUMN "PAYMENT"."PAY_DATE" IS '결제 완료 일시';

COMMENT ON COLUMN "PAYMENT"."PAY_REGIST" IS '생성일';

CREATE TABLE "SETTLEMENT_REQUEST" (
	"SR_NO"	NUMBER		NOT NULL,
	"SR_TYPE"	CHAR(1)		NULL,
	"SR_TARGET_NO"	NUMBER		NULL,
	"WORK_NO"	NUMBER		NULL,
	"SR_MONTH"	CHAR(7)		NULL,
	"SR_START"	DATE		NULL,
	"SR_END"	DATE		NULL,
	"TOTAL_SALES"	NUMBER		NULL,
	"SR_AMOUNT"	NUMBER		NULL,
	"REQUEST_DATE"	DATE		NULL,
	"SR_STATUS"	CHAR(1)		NULL,
	"PAYMENT_DATE"	DATE		NULL,
	"ADMIN_NO"	NUMBER		NULL,
	"SR_MOD"	DATE		NULL
);

COMMENT ON COLUMN "SETTLEMENT_REQUEST"."SR_TYPE" IS 'A(자유작가) | P(출판사)';

COMMENT ON COLUMN "SETTLEMENT_REQUEST"."WORK_NO" IS '정산요청 작품번호';

COMMENT ON COLUMN "SETTLEMENT_REQUEST"."SR_MONTH" IS '정산월(2026-06)';

COMMENT ON COLUMN "SETTLEMENT_REQUEST"."SR_START" IS '판매시작일';

COMMENT ON COLUMN "SETTLEMENT_REQUEST"."TOTAL_SALES" IS '총 판매금액';

COMMENT ON COLUMN "SETTLEMENT_REQUEST"."SR_AMOUNT" IS '지급금액(최종 정산금액)';

COMMENT ON COLUMN "SETTLEMENT_REQUEST"."SR_STATUS" IS '미요청(N) | 정산요청/정산대기(W) | 정산완료(C)';

COMMENT ON COLUMN "SETTLEMENT_REQUEST"."ADMIN_NO" IS '처리 관리자';

CREATE TABLE "ACCUSE_MENU" (
	"ACCMENU_NO"	NUMBER		NOT NULL,
	"ACCMENU_CODE"	VARCHAR2(20)		NULL,
	"ACCMENU_NAME"	VARCHAR2(50)		NULL,
	"ACCMENU_DESC"	CLOB		NULL
);

CREATE TABLE "ADMIN_AUTH" (
	"ADMIN_NO"	NUMBER		NULL,
	"AA_BOD"	CHAR(1)		NULL,
	"AA_POST"	CHAR(1)		NULL,
	"AA_EPI"	CHAR(1)		NULL,
	"AA_EVT"	CHAR(1)		NULL,
	"AA_KEY"	CHAR(1)		NULL,
	"AA_WRITER"	CHAR(1)		NULL,
	"AA_PUB"	CHAR(1)		NULL,
	"AA_SETTLE"	CHAR(1)		NULL,
	"AA_QNA"	CHAR(1)		NULL,
	"AA_MEM"	CHAR(1)		NULL,
	"SUPER_ADMIN"	CHAR(1)		NULL
);

CREATE TABLE "PUB_MEM" (
	"PUB_NO"	NUMBER		NULL,
	"MEM_NO"	NUMBER		NULL
);

CREATE TABLE "QNA" (
	"QNA_NO"	NUMBER		NOT NULL,
	"MEM_NO"	NUMBER		NULL,
	"QNA_TITLE"	VARCHAR2(300)		NULL,
	"QNA_CONTENT"	VARCHAR2(1500)		NULL,
	"QNA_REG"	DATE	DEFAULT SYSDATE	NULL,
	"QNA_MOD"	DATE	DEFAULT SYSDATE	NULL,
	"ANSWER_YN"	CHAR(1)		NULL,
	"ANSWER_CONTENT"	VARCHAR2(4000)		NULL,
	"ADMIN_NO"	NUMBER		NULL,
	"ANSWER_REG"	DATE		NULL,
	"ANSWER_MOD"	DATE		NULL,
	"DEL_YN"	CHAR(1)	DEFAULT 'N'	NULL
);

COMMENT ON COLUMN "QNA"."DEL_YN" IS 'Y | N';

CREATE TABLE "EP_FREE_EVT" (
	"EPEVT_NO"	NUMBER		NOT NULL,
	"EVT_NO"	NUMBER		NULL,
	"WORK_NO"	NUMBER		NULL,
	"EPEVT_CNT"	NUMBER		NULL
);

CREATE TABLE "GENRE" (
	"GENRE_NO"	NUMBER		NOT NULL,
	"GENRE_TYPE"	CHAR(1)		NULL,
	"GENRE_NAME"	VARCHAR2(30)		NULL,
	"GENRE_PARENT"	NUMBER		NULL,
	"SORT_ORDER"	NUMBER		NULL
);

COMMENT ON COLUMN "GENRE"."GENRE_TYPE" IS '큰분류(M) |세부장르(S)';

CREATE TABLE "WRITER" (
	"WRITER_NO"	NUMBER		NOT NULL,
	"PUB_NO"	NUMBER		NULL,
	"MEM_NO"	NUMBER		NULL,
	"WRITER_NAME"	VARCHAR2(60)		NULL,
	"WRITER_INFO"	VARCHAR2(1000)		NULL,
	"WRITER_REG"	DATE		NULL,
	"WRITER_MOD"	DATE		NULL,
	"WRITER_STATUS"	CHAR(1)		NULL,
	"WORK_PANALTY"	NUMBER		NULL
);

COMMENT ON COLUMN "WRITER"."PUB_NO" IS '출판사|자유';

COMMENT ON COLUMN "WRITER"."WRITER_STATUS" IS 'A(활성) | I (비활성) | S(규제중)';

CREATE TABLE "BLOCK_LIST" (
	"MEM_NO"	NUMBER		NULL,
	"BLOCK_NO"	NUMBER		NULL,
	"BLOCK_DATE"	DATE	DEFAULT SYSDATE	NULL
);

CREATE TABLE "WORK_NOTICE" (
	"WN_NO"	NUMBER		NOT NULL,
	"WORK_NO"	NUMBER		NOT NULL,
	"WN_TITLE"	VARCHAR2(300)		NOT NULL,
	"WN_CONTENT"	VARCHAR2(3000)		NOT NULL,
	"MEM_NO"	NUMBER		NOT NULL,
	"WN_REG"	DATE		NULL,
	"WN_MOD"	DATE		NULL,
	"DEL_YN"	CHAR(1)	DEFAULT 'N'	NULL
);

COMMENT ON COLUMN "WORK_NOTICE"."DEL_YN" IS 'Y/N';

CREATE TABLE "PUBLISHER" (
	"PUB_NO"	NUMBER		NOT NULL,
	"PUB_NAME"	VARCHAR2(50)		NULL,
	"PUB_INC"	VARCHAR2(100)		NULL,
	"PUB_BRN"	CHAR(12)		NULL,
	"PUB_ADDRESS"	VARCHAR2(500)		NULL,
	"PUB_PHONE"	VARCHAR2(13)		NULL,
	"PUB_EMAIL"	VARCHAR2(50)		NULL,
	"PUB_CONTRACT"	DATE	DEFAULT SYSDATE	NULL,
	"PUB_MODIFY"	DATE	DEFAULT SYSDATE	NULL,
	"PUB_RECENT"	DATE	DEFAULT SYSDATE	NULL,
	"PUB_BANK"	VARCHAR2(30)		NULL,
	"PUB_ACCNO"	VARCHAR2(14)		NULL,
	"PUB_ACCNAME"	VARCHAR2(100)		NULL
);

COMMENT ON COLUMN "PUBLISHER"."PUB_BRN" IS '- 포함';

CREATE TABLE "MEMBER" (
	"MEM_NO"	NUMBER		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_PW"	VARCHAR2(100)		NULL,
	"MEM_NAME"	VARCHAR2(20)		NOT NULL,
	"MEM_EMAIL"	VARCHAR2(50)		NOT NULL,
	"MEM_NICKNAME"	VARCHAR2(30)		NULL,
	"MEM_PHONE"	NUMBER		NOT NULL,
	"MEM_LEVEL"	CHAR(1)		NULL,
	"MEM_BANK"	VARCHAR2(20)		NULL,
	"BANK_NUM"	NUMBER		NULL,
	"MEM_POINT"	NUMBER	DEFAULT 0	NOT NULL,
	"MEM_PROFILE"	VARCHAR2(500)		NULL,
	"ADULT_YN"	CHAR(1)		NULL,
	"MEM_STATUS"	CHAR(1)		NOT NULL,
	"MEM_REG"	DATE	DEFAULT SYSDATE	NULL,
	"MEM_END"	DATE		NULL,
	"POST_PANALTY"	NUMBER		NULL,
	"WORK_PANALTY"	NUMBER		NULL,
	"FAVOR_YN"	CHAR(1)	DEFAULT 'Y'	NOT NULL,
	"BOARD_YN"	CHAR(1)	DEFAULT 'Y'	NOT NULL,
	"MYWORK_YN"	CHAR(1)	DEFAULT 'Y'	NOT NULL,
	"MEM_MODIFY"	DATE	DEFAULT SYSDATE	NULL,
	"LOGIN_TYPE"	CHAR(1)	DEFAULT 'L'	NOT NULL,
	"SOCIAL_ID"	VARCHAR2(100)		NULL
);

COMMENT ON COLUMN "MEMBER"."ADULT_YN" IS 'Y|N';

COMMENT ON COLUMN "MEMBER"."MEM_STATUS" IS '정상(A) | 탈퇴(N) | 컨텐츠작성X(S) | 비활성(I)';

COMMENT ON COLUMN "MEMBER"."POST_PANALTY" IS '작성게시글 관련';

COMMENT ON COLUMN "MEMBER"."FAVOR_YN" IS 'Y / N';

COMMENT ON COLUMN "MEMBER"."BOARD_YN" IS 'Y / N';

COMMENT ON COLUMN "MEMBER"."MYWORK_YN" IS 'Y / N';

COMMENT ON COLUMN "MEMBER"."MEM_MODIFY" IS '알림 수정X';

COMMENT ON COLUMN "MEMBER"."LOGIN_TYPE" IS 'L:로컬 ,K:카카오 ,G:구글 ,N:네이버';

CREATE TABLE "EVENT" (
	"EVT_NO"	NUMBER		NOT NULL,
	"EVT_TYPE"	CHAR(1)		NULL,
	"EVT_TITLE"	VARCHAR2(300)		NULL,
	"EVT_CONTENT"	VARCHAR2(4000)		NULL,
	"MEM_NO"	NUMBER		NULL,
	"EVT_REG"	DATE	DEFAULT SYSDATE	NULL,
	"EVT_START"	DATE		NULL,
	"EVT_END"	DATE		NULL,
	"EVT_THUMBNAIL"	VARCHAR2(1000)		NULL,
	"GENRE_NO"	NUMBER		NULL,
	"EVT_STATUS"	CHAR(1)		NULL
);

COMMENT ON COLUMN "EVENT"."EVT_TYPE" IS '작품(W) | 할인(D)';

COMMENT ON COLUMN "EVENT"."EVT_THUMBNAIL" IS '이벤트썸네일이미지URL';

COMMENT ON COLUMN "EVENT"."GENRE_NO" IS '장르테이블FK & 전체는 0';

COMMENT ON COLUMN "EVENT"."EVT_STATUS" IS '예약(P) | 진행(A) | 종료(C)';

CREATE TABLE "MEM_COUPON" (
	"MC_NO"	NUMBER		NOT NULL,
	"COUPON_NO"	NUMBER		NULL,
	"MEM_NO"	NUMBER		NULL,
	"ISSUE_AT"	DATE		NULL,
	"EXPIRE_AT"	DATE		NULL,
	"USED_AT"	DATE		NULL,
	"MC_STATUS"	CHAR(1)		NULL
);

COMMENT ON COLUMN "MEM_COUPON"."MC_NO" IS 'MC_1  ?';

COMMENT ON COLUMN "MEM_COUPON"."MC_STATUS" IS '사용가능(A) | 사용완료(U) | 기간만료(E)';

CREATE TABLE "FOR_FILTER" (
	"WORK_NO"	NUMBER		NULL,
	"KEY_NO"	NUMBER		NULL
);

CREATE TABLE "COMMENT" (
	"COM_NO"	NUMBER		NOT NULL,
	"MEM_NO"	NUMBER		NULL,
	"COM_TYPE"	CHAR(1)		NULL,
	"BOARD_NO"	NUMBER		NULL,
	"COM_CONTENT"	VARCHAR2(1500)		NULL,
	"COM_PARENT"	NUMBER		NULL,
	"COM_REGIST"	DATE	DEFAULT SYSDATE	NULL,
	"COM_MODIFY"	DATE	DEFAULT SYSDATE	NULL,
	"COM_STATUS"	CHAR(1)	DEFAULT 'A'	NULL
);

COMMENT ON COLUMN "COMMENT"."COM_TYPE" IS '게시글(B)|회차(E)';

COMMENT ON COLUMN "COMMENT"."COM_STATUS" IS '정상(A)|삭제(D)|규제(S)';

CREATE TABLE "WRITER_REQUEST" (
	"WR_NO"	NUMBER		NOT NULL,
	"MEM_NO"	NUMBER		NULL,
	"WR_REG"	DATE	DEFAULT SYSDATE	NULL,
	"WR_STATUS"	CHAR(1)		NULL,
	"WR_MOD"	DATE	DEFAULT SYSDATE	NULL,
	"WR_ADMIN"	NUMBER		NULL
);

COMMENT ON COLUMN "WRITER_REQUEST"."WR_STATUS" IS '요청대기(P) | 승인(A) | 반려(R)';

CREATE TABLE "KEYWORD" (
	"KEY_NO"	NUMBER		NOT NULL,
	"GENRE_NO"	NUMBER		NOT NULL,
	"KEY_TYPE"	CHAR(1)		NOT NULL,
	"KEY_NAME"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "KEYWORD"."KEY_TYPE" IS '소재|주인공|직업|분위기|관계';

CREATE TABLE "WORK" (
	"WORK_NO"	NUMBER		NOT NULL,
	"WORK_TITLE"	VARCHAR2(150)		NULL,
	"PUB_NO"	NUMBER		NULL,
	"WRITER_NO"	NUMBER		NULL,
	"WORK_INFO"	VARCHAR2(1000)		NULL,
	"WORK_COVER"	VARCHAR2(500)		NULL,
	"GENRE_NO"	CHAR(1)		NULL,
	"ADULT_YN"	CHAR(1)		NULL,
	"PAID_YN"	CHAR(1)		NULL,
	"WORK_REG"	DATE	DEFAULT SYSDATE	NOT NULL,
	"WORK_LATEST"	DATE	DEFAULT SYSDATE	NULL,
	"WORK_FAVCNT"	NUMBER		NULL,
	"WORK_MOD"	DATE		NULL,
	"SERIAL_STATUS"	CHAR(1)		NULL,
	"WORK_STATUS"	CHAR(1)		NULL
);

COMMENT ON COLUMN "WORK"."WRITER_NO" IS '자유일때만';

COMMENT ON COLUMN "WORK"."GENRE_NO" IS '세부장르코드';

COMMENT ON COLUMN "WORK"."PAID_YN" IS '유료(P)|무료(F)';

COMMENT ON COLUMN "WORK"."SERIAL_STATUS" IS '연재(O)|휴재(P)|완결(C)|중단(S)';

COMMENT ON COLUMN "WORK"."WORK_STATUS" IS '숨김(H) | 삭제(D) | 정상(A)';

CREATE TABLE "EPISODE" (
	"EPI_NO"	NUMBER		NOT NULL,
	"WORK_NO"	NUMBER		NOT NULL,
	"EPI_TITLE"	VARCHAR2(200)		NOT NULL,
	"EPI_CONTENT"	CLOB		NOT NULL,
	"EPI_REG"	DATE	DEFAULT SYSDATE	NULL,
	"EPI_MOD"	DATE	DEFAULT SYSDATE	NULL,
	"PAID_YN"	CHAR(1)		NULL,
	"EPI_STATUS"	CHAR(1)		NULL,
	"EPI_COUNT"	NUMBER		NULL,
	"OPEN_AT"	DATE		NULL
);

COMMENT ON COLUMN "EPISODE"."EPI_STATUS" IS '삭제(D) | 숨김(H) |규제(S) |정상(A)';

COMMENT ON COLUMN "EPISODE"."OPEN_AT" IS '후순위';

CREATE TABLE "POINT_DETAIL" (
	"PD_NO"	NUMBER		NOT NULL,
	"PH_NO"	NUMBER		NULL,
	"MEM_NO"	NUMBER		NULL,
	"WORK_NO"	NUMBER		NULL,
	"EPI_NO"	NUMBER		NULL,
	"PD_STATUS"	CHAR(1)		NULL
);

COMMENT ON COLUMN "POINT_DETAIL"."PD_STATUS" IS '(P)URCHASED | (R)EFUND';

CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"BOARD_TYPE"	CHAR(1)		NULL,
	"BOARD_TITLE"	VARCHAR2(300)		NULL,
	"BOARD_CONTENT"	CLOB		NULL,
	"MEM_NO"	NUMBER		NULL,
	"BOARD_REG"	DATE		NULL,
	"BOARD_MOD"	DATE		NULL,
	"BOARD_STATUS"	CHAR(1)	DEFAULT 'A'	NULL,
	"POST_TYPE"	CHAR(1)		NULL,
	"BOARD_COUNT"	NUMBER		NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_TYPE" IS '달글(B)|독자(R)|작가(W)';

COMMENT ON COLUMN "BOARD"."BOARD_STATUS" IS '정상(A) | 삭제(D) |규제(S)';

COMMENT ON COLUMN "BOARD"."POST_TYPE" IS '일반|공지';

CREATE TABLE "POINT_HISTORY" (
	"PH_NO"	NUMBER		NOT NULL,
	"MEM_NO"	NUMBER		NULL,
	"PH_TYPE"	VARCHAR2(6)		NULL,
	"PH_CHANGE"	NUMBER		NULL,
	"COUPON_NO"	NUMBER		NULL,
	"PH_ORIGIN"	NUMBER		NULL,
	"PH_DATE"	DATE	DEFAULT SYSDATE	NULL
);

COMMENT ON COLUMN "POINT_HISTORY"."PH_TYPE" IS 'CHARGE(충전) | USE(사용) | CANCEL(취소)';

COMMENT ON COLUMN "POINT_HISTORY"."COUPON_NO" IS '보유쿠폰아이디 | 없으면 NULL';

CREATE TABLE "ATTACHMENT" (
	"ATT_NO"	NUMBER		NOT NULL,
	"REF_NO"	NUMBER		NULL,
	"REF_CATEGORY"	VARCHAR2(30)		NULL,
	"ATT_ORIGIN"	VARCHAR2(300)		NULL,
	"FILESYSTEM_NAME"	VARCHAR2(300)		NULL,
	"ATT_PATH"	VARCHAR2(300)		NULL,
	"ATT_REG"	DATE	DEFAULT SYSDATE	NULL,
	"ATT_MOD"	DATE	DEFAULT SYSDATE	NULL,
	"DEL_YN"	CHAR(1)	DEFAULT 'N'	NULL,
	"REG_ID"	NUMBER		NULL,
	"MOD_ID"	NUMBER		NULL
);

COMMENT ON COLUMN "ATTACHMENT"."DEL_YN" IS 'Y/N';

CREATE TABLE "LIBRARY" (
	"LIB_NO"	NUMBER		NOT NULL,
	"MEM_NO"	NUMBER		NULL,
	"WORK_NO"	NUMBER		NULL,
	"EPI_NO"	NUMBER		NULL,
	"LAST_DATE"	DATE		NULL,
	"PURCHASE_DATE"	DATE		NULL,
	"FAVORITE_DATE"	DATE		NULL,
	"WISH_DATE"	DATE		NULL,
	"FAVORITE_YN"	CHAR(1)	DEFAULT 'Y'	NULL
);

COMMENT ON COLUMN "LIBRARY"."FAVORITE_YN" IS 'Y | N';

CREATE TABLE "NOTIFICATION" (
	"NOTI_NO"	NUMBER		NOT NULL,
	"MEM_NO"	NUMBER		NULL,
	"NOTI_TYPE"	CHAR(1)		NULL,
	"NOTI_CONTENT"	VARCHAR2(4000)		NULL,
	"READ_YN"	CHAR(1)	DEFAULT 'N'	NULL,
	"DEL_YN"	CHAR(1)	DEFAULT 'N'	NULL,
	"NOTI_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"NOTI_URL"	VARCHAR2(4000)		NULL
);

COMMENT ON COLUMN "NOTIFICATION"."READ_YN" IS 'Y|N';

COMMENT ON COLUMN "NOTIFICATION"."DEL_YN" IS 'Y|N';

CREATE TABLE "ACCUSE" (
	"ACC_NO"	NUMBER		NOT NULL,
	"MEM_NO"	NUMBER		NULL,
	"TARGET_TYPE"	CHAR(1)		NULL,
	"TARGET_ID"	NUMBER		NULL,
	"ACCMENU_NO"	NUMBER		NULL,
	"ACC_CONTENT"	VARCHAR2(4000)		NULL,
	"TARGET_NO"	NUMBER		NULL,
	"ACC_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"ACC_STATUS"	CHAR(1)		NULL,
	"ADMIN_NO"	NUMBER		NULL,
	"ACC_REASON"	VARCHAR2(2000)		NULL,
	"ACC_MODIFY"	DATE	DEFAULT SYSDATE	NULL
);

COMMENT ON COLUMN "ACCUSE"."TARGET_TYPE" IS '작성글(POST) | 댓글(COMMENT) | 작품회차(EPISODE)';

COMMENT ON COLUMN "ACCUSE"."TARGET_ID" IS '신고된 컨텐츠 번호';

COMMENT ON COLUMN "ACCUSE"."ACCMENU_NO" IS '신고유형';

COMMENT ON COLUMN "ACCUSE"."TARGET_NO" IS '신고된 회원';

COMMENT ON COLUMN "ACCUSE"."ACC_STATUS" IS '대기(P) | 규제(S) | 기각(R) | 수정요청(U)';

CREATE TABLE "COUPON" (
	"COUPON_NO"	NUMBER		NOT NULL,
	"EVT_NO"	NUMBER		NULL,
	"DISCOUNT_DATE"	NUMBER		NULL,
	"COUPON_DATE"	DATE		NULL,
	"COUPON_EXP"	DATE		NULL
);

COMMENT ON COLUMN "COUPON"."COUPON_NO" IS 'COU_1';

CREATE TABLE "SUBSCRIBE" (
	"MEM_NO"	NUMBER		NOT NULL,
	"WRITER_NO"	NUMBER		NOT NULL,
	"SUB_DATE"	DATE	DEFAULT SYSDATE	NULL
);

ALTER TABLE "PAYMENT" ADD CONSTRAINT "PK_PAYMENT" PRIMARY KEY (
	"PAY_NO"
);

ALTER TABLE "SETTLEMENT_REQUEST" ADD CONSTRAINT "PK_SETTLEMENT_REQUEST" PRIMARY KEY (
	"SR_NO"
);

ALTER TABLE "ACCUSE_MENU" ADD CONSTRAINT "PK_ACCUSE_MENU" PRIMARY KEY (
	"ACCMENU_NO"
);

ALTER TABLE "QNA" ADD CONSTRAINT "PK_QNA" PRIMARY KEY (
	"QNA_NO"
);

ALTER TABLE "EP_FREE_EVT" ADD CONSTRAINT "PK_EP_FREE_EVT" PRIMARY KEY (
	"EPEVT_NO"
);

ALTER TABLE "GENRE" ADD CONSTRAINT "PK_GENRE" PRIMARY KEY (
	"GENRE_NO"
);

ALTER TABLE "WRITER" ADD CONSTRAINT "PK_WRITER" PRIMARY KEY (
	"WRITER_NO"
);

ALTER TABLE "WORK_NOTICE" ADD CONSTRAINT "PK_WORK_NOTICE" PRIMARY KEY (
	"WN_NO"
);

ALTER TABLE "PUBLISHER" ADD CONSTRAINT "PK_PUBLISHER" PRIMARY KEY (
	"PUB_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEM_NO"
);

ALTER TABLE "EVENT" ADD CONSTRAINT "PK_EVENT" PRIMARY KEY (
	"EVT_NO"
);

ALTER TABLE "MEM_COUPON" ADD CONSTRAINT "PK_MEM_COUPON" PRIMARY KEY (
	"MC_NO"
);

ALTER TABLE "FOR_FILTER" ADD CONSTRAINT "PK_FOR_FILTER" PRIMARY KEY (
	"WORK_NO",
	"KEY_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
	"COM_NO"
);

ALTER TABLE "WRITER_REQUEST" ADD CONSTRAINT "PK_WRITER_REQUEST" PRIMARY KEY (
	"WR_NO"
);

ALTER TABLE "KEYWORD" ADD CONSTRAINT "PK_KEYWORD" PRIMARY KEY (
	"KEY_NO"
);

ALTER TABLE "WORK" ADD CONSTRAINT "PK_WORK" PRIMARY KEY (
	"WORK_NO"
);

ALTER TABLE "EPISODE" ADD CONSTRAINT "PK_EPISODE" PRIMARY KEY (
	"EPI_NO"
);

ALTER TABLE "POINT_DETAIL" ADD CONSTRAINT "PK_POINT_DETAIL" PRIMARY KEY (
	"PD_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "POINT_HISTORY" ADD CONSTRAINT "PK_POINT_HISTORY" PRIMARY KEY (
	"PH_NO"
);

ALTER TABLE "ATTACHMENT" ADD CONSTRAINT "PK_ATTACHMENT" PRIMARY KEY (
	"ATT_NO"
);

ALTER TABLE "LIBRARY" ADD CONSTRAINT "PK_LIBRARY" PRIMARY KEY (
	"LIB_NO"
);

ALTER TABLE "NOTIFICATION" ADD CONSTRAINT "PK_NOTIFICATION" PRIMARY KEY (
	"NOTI_NO"
);

ALTER TABLE "ACCUSE" ADD CONSTRAINT "PK_ACCUSE" PRIMARY KEY (
	"ACC_NO"
);

ALTER TABLE "COUPON" ADD CONSTRAINT "PK_COUPON" PRIMARY KEY (
	"COUPON_NO"
);

ALTER TABLE "SUBSCRIBE" ADD CONSTRAINT "PK_SUBSCRIBE" PRIMARY KEY (
	"MEM_NO",
	"WRITER_NO"
);

-- MEM_ID 값 NULL 허용
ALTER TABLE MEMBER
MODIFY MEM_ID NULL;

-- 회원 상태 기본값 Y
ALTER TABLE MEMBER
MODIFY MEM_STATUS DEFAULT 'Y';

-- 통계용 출생연도, 성별 컬럼 추가
ALTER TABLE MEMBER ADD (
    BIRTH_YEAR NUMBER(4),
    GENDER     CHAR(1)
);

-- 회원번호용 시퀀스 생성
CREATE SEQUENCE SEQ_MNO
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;